# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - 'releases/**'
  release:
    types: [created]

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:

      # CHECKOUT
      - name: checkout
        uses: actions/checkout@v1

      # SETUP
      - name: setup
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Configure CI Git User
        run: |
          git config --global user.name '@corlogixco'
          git config --global user.email 'corlogixco@gmail.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
          git remote -v
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Authenticate with Registry
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # INSTAL
      - run: npm ci

      # BUILD
      - run: npm run build

      # PUBLISH
      - run: npm run publish

  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org/
  #     - run: |
  #         git config --global user.name corlogix
  #         git config --global user.email corlogixco@gmail.com
  #     - run: npm ci
  #     - run: npm run build
  #     - run: npm run publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}